# Generated by Django 2.2.12 on 2020-06-21 22:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='push',
            managers=[
                ('count', django.db.models.manager.Manager()),
            ],
        ),
    ]
