# Generated by Django 2.2.12 on 2020-06-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20200622_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='push',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
